### ISSUE TITLE
ODM-protocol.xsd missing type for StudyInterventionOID

### ISSUE THREAD

**Issue by TeMeta** [cdisc-org/DataExchange-ODM#48]
```
    <xs:attributeGroup name="StudyInterventionRefAttributeDefinition">
        <xs:attribute name="StudyInterventionOID" use="required"/>
```

**Comment by lexjansen** [comment]
Thanks! This should obviously be type="oidref".
The specification is also incorrect: https://wiki.cdisc.org/display/ODM2/StudyInterventionRef
It has StudyEventOID instead of StudyInterventionOID.
I will fix those.

**Comment by lexjansen** [comment]
fixed on dev
